# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 23:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='precio',
            field=models.FloatField(),
        ),
    ]
