# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relevamiento', '0002_auto_20160203_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={'ordering': ['-anio', '-mes', '-quincena']},
        ),
        migrations.AlterModelOptions(
            name='planilladerelevamiento',
            options={'ordering': ['planilla_modelo__nombre', 'zona'], 'verbose_name_plural': 'planillas de relevamiento'},
        ),
        migrations.AlterField(
            model_name='comercio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to='relevamiento.Zona'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='planilla_de_relevamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='relevamiento.PlanillaDeRelevamiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='relevamiento.Zona'),
        ),
        migrations.AlterField(
            model_name='planilladerelevamiento',
            name='comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_de_relevamiento', to='relevamiento.Comercio'),
        ),
        migrations.AlterField(
            model_name='planilladerelevamiento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_de_relevamiento', to='relevamiento.Zona'),
        ),
    ]
